name: baderkit_dev
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.10  # Before this there is no importlib.metadata

  # Core dependencies (with version caps)
  - pymatgen>=2022.1.9,<=2025.6.14
  - numpy>=1.26.0,<3.0
  - pandas>=2.1.0,<3.0
  - scipy>=1.7.2,<2.0
  - numba>=0.59.0,<=0.61.2
  - typer>=0.6.1,<=0.16.0
  - rich>=11.0,<=14.0
  - pyvista>=0.44.0,<0.45.2
  - pyvistaqt

  # Preferred IDE
  - spyder

  # Documentation
  - mkdocs-material>=9.5.44
  - mkdocstrings>=0.25.2
  - mkdocstrings-python>=1.10.9

  # Testing and pip
  - h5py
  - pytest
