name: baderkit_dev
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.10 # Before this there is no importlib.metadata
  - pymatgen>=2022.1.9 # Same as Simmate's
  - numpy>=1.26.0 # Could potentially be earlier
  - pandas>=2.1.0 # Prior to this, they use applymap instead of map
  - typer>=0.6.1 
  - rich>=11.0 # Same as simmate
  - numba>=0.59.0
  - scipy>=1.7.2 # Added python 3.10 support
  # prefered IDE
  - spyder
  # docs
  - mkdocs-material >=9.5.44
  - mkdocstrings >=0.25.2
  - mkdocstrings-python >=1.10.9
  # packages for plotting
  - streamlit>=1.40.0 # Added st.segmented_control
  - pip
  - pip:
      - pyvista[jupyter]>=0.44.0
